### ISSUE TITLE
Can't run downloaded darwin binary on M2 Max Mac

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/awm-relayer#190]
Get a MacOS Gatekeeper error message after downloading the Darwin tar.gz binary and running the following command:
```
tar -xvf $HOME/downloads/awm-relayer_0.2.13_darwin_arm64.tar.gz -C $HOME/my-path
chmod +x awm-relayer
./awm-relayer --config-file $HOME/path-to/relayer-config.json
```

![image](https://github.com/ava-labs/awm-relayer/assets/99047250/2340a95b-a4b1-4486-a660-8f08275a74f1)

**Comment by cam-schultz** [comment]
We should include something similar to [this](https://github.com/ava-labs/hypersdk/blob/968ecec17a8ebb4a3067513d4bab951f1949243d/examples/tokenvm/cmd/token-wallet/scripts/build.sh#L41-L54) when building the release.

In the meantime, the binary can be allowed manually through system preferences.

**Comment by cam-schultz** [comment]
This is due to the quarantine attribute being set by browsers when downloading executables that have not been notarized by Apple (i.e. have not been approved by the App Store).

We're not going to go through that process, so the workarounds are to either 1) download the binary tarball via curl or wget (which does not set the quarantine attribute) or 2) remove the quarantine attribute by running `xattr -d com.apple.quarantine awm-relayer`. See here for a similar discussion: https://github.com/ninja-build/ninja/issues/1695.

https://github.com/ava-labs/awm-relayer/pull/197 documents this explicitly.
