### ISSUE TITLE
Failed to relay messages; missing BLS keys?

### ISSUE THREAD

**Issue by tactical-retreat** [ava-labs/awm-relayer#207]
**Describe the bug**

Relaying is failing for me with `failed to collect a threshold of signatures`. 

Just looked up my testnet [validation registration](https://subnets-test.avax.network/p-chain/tx/hfaMFwXGEnfSXTa5de7w9LRLZ753iMdy7azpdYiYDrgd5Zfj) and it seems to have used `AddValidatorTx` so I'm guessing that I have no BLS keys registered for the nodes validating my subnet.

Am I right that this is the root cause of the relaying failure?

Is this fixable for the existing validations? Or do I have to wipe the keys on my nodes and reregister them?

**Comment by cam-schultz** [comment]
Hi @tactical-retreat , yes your understanding is correct that `AddValidatorTx` does not register the node's BLS key, so it will not be able to sign Warp messages. Validation periods cannot be cancelled, so the only fix is to wait for the validation period to end, then re-register using `AddPermissionlessValidatorTx`. Note that in Avalanchego v1.11.0, `AddValidatorTx` is disabled altogether after the Durango activation time at 4PM UTC March 6.

> Or do I have to wipe the keys on my nodes and reregister them?

This should work, though half of your subnet's validators will not be able to sign Warp messages. The default signing threshold is 67% of stake weight, so just make sure that when registering the new validators that you stake enough so that they account for 67% of the subnet's new total stake.

I'm going to close this issue since it's not an `awm-relayer` bug, and because new validations using `AddValidatorTx` are impossible after the Durango network upgrade takes effect.
