### ISSUE TITLE
Properly manage relayer EOA nonce

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/awm-relayer#6]
**Context and scope**
Currently, we get the nonce on startup, and manage it in the relayer application. If the relayer EOA is used elsewhere, the in-memory nonce will not match the account nonce. We should account for this.

**Discussion and alternatives**
One likely place this could come up is if the same private key is used by multiple relayers.

There's no to safely manage the same nonce across multiple relayer instances without having the processes synchronize in some way. A more practical approach would be to have each relayer instance uniquely use a private key.

**Comment by cam-schultz** [comment]
The generally accepted nonce management best practice is to fetch the nonce once and then manage it within the application, rather than attempting to re-sync the nonce from the chain. Implied by this is that a private key should only be used to send transactions from a single source. Therefore, the nonce management strategy we will take with `awm-relayer` is to ensure every instance is composed with its own unique private key. No code changes needed.
