### ISSUE TITLE
Rename "chainID" to "blockchainID"

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#70]
**Context and scope**
Throughout the relayer implementation, the name `chainID` is used to refer to the Avalanche blockchain ID, i.e. the tx hash that created the blockchain. This is easily confused with the EVM chainID, returned by `eth_chainId`

**Discussion and alternatives**
We should replace all usages of `chainID` with `blockchainID`. We do not use the EVM chain ID for any purpose.

**Open questions**
Questions that are still being discussed.

**Comment by geoff-vball** [comment]
Note: We DO use `chainID` in at least a few places. It's set in the genesis file as `99999`, and is needed if we want to get a transactor from the `bind` package.

What's the difference between `subnetID` and `chainID` in the current implementation? It kind of seems like they're used to be the same thing here.

`blockchainID` is an `ids.ID` from avalanchego, which is a `[32]byte`. Are we able to enter the ID in the viper config so that it gets parsed as a `[32]byte`? Right now everything is parsed as a string, and I think that's leading to some confusion. 

Another note: `chainID` (the ethereum kind) is a `*big.Int`, so it should be distinct from `blockchainID` everywhere.
